apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mongodb
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flicknote-infra
  path: ./flux/mongodb/base
  prune: true
  wait: true
  timeout: 5m
