apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka
  namespace: flicknote-infra
spec:
  interval: 30m
  chart:
    spec:
      chart: ./charts/kafka
      sourceRef:
        kind: GitRepository
        name: flicknote-infra
        namespace: flux-system
      reconcileStrategy: Revision
  install:
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    remediation:
      retries: 3
    timeout: 10m
  values:
    replicas: 1
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "1"
    storage:
      size: 10Gi
