apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: flicknote-infra
spec:
  interval: 30m
  releaseName: redis
  chart:
    spec:
      chart: ./charts/redis
      sourceRef:
        kind: GitRepository
        name: flicknote-infra
        namespace: flux-system
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
    timeout: 10m
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    timeout: 10m
  values:
    image:
      repository: redis
      tag: "7"
      pullPolicy: IfNotPresent

    config:
      appendonly: true

    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "200m"

    persistence:
      enabled: true
      storageClass: local-path
      size: 2Gi
