apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: flicknote-infra
spec:
  interval: 30m
  releaseName: mongodb
  chart:
    spec:
      chart: ./charts/mongodb
      sourceRef:
        kind: GitRepository
        name: flicknote-infra
        namespace: flux-system
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
    timeout: 10m
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    timeout: 10m
  values:
    image:
      repository: mongo
      tag: "7.0"
      pullPolicy: IfNotPresent

    replicaSet:
      name: rs0

    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"

    persistence:
      enabled: true
      storageClass: local-path
      size: 5Gi
